version: "3.9"
services:
  app_portal_noticias:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app_portal_noticias
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      dblaravel:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:80"

  dblaravel:
    image: "mysql/mysql-server:8.0"
    container_name: dblaravel
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sql-data-dblaravel:

networks:
  default:
    name: appportalnoticias
